---
  extends:
    - "airbnb"

  env:
    browser: true
    node: true
    es6: true
    jest: true

  parserOptions:
   ecmaVersion: 6
   sourceType: "module"
   ecmaFeatures:
    jsx: true

  globals:
    __DEV__: true
    __SERVER__: true

  plugins:
    - react
    - jest
